description = "A about theme with blog"
homepage = "https://github.com/getzola/hyde"
license = "MIT"
name = "modhax theme"
# The minimum version of Zola required
min_version = "0.16.0"
# An optional live demo URL
demo = "https://www.modhax-theme.dev"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
homepage = "https://modhax.dev"
name = "Florian Drews"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author = "mdo"
homepage = "https://markdotto.com/"
repo = "https://www.github.com/mdo/hyde"
